
# This file is automatically generated, you probably don't want to edit this

ContTabHTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ContTabHTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            compare = "rows",
            obs = TRUE,
            exp = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            pcTot = FALSE,
            reps = 100,
            dotHist = "dotplot",
            showCounts = FALSE,
            seedBool = FALSE,
            rngSeed = 8675309, ...) {

            super$initialize(
                package="Randomize",
                name="ContTabHTest",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..compare <- jmvcore::OptionList$new(
                "compare",
                compare,
                options=list(
                    "rows",
                    "columns"),
                default="rows")
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=TRUE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcTot <- jmvcore::OptionBool$new(
                "pcTot",
                pcTot,
                default=FALSE)
            private$..reps <- jmvcore::OptionNumber$new(
                "reps",
                reps,
                default=100)
            private$..dotHist <- jmvcore::OptionList$new(
                "dotHist",
                dotHist,
                options=list(
                    "dotplot",
                    "histogram"),
                default="dotplot")
            private$..showCounts <- jmvcore::OptionBool$new(
                "showCounts",
                showCounts,
                default=FALSE)
            private$..seedBool <- jmvcore::OptionBool$new(
                "seedBool",
                seedBool,
                default=FALSE)
            private$..rngSeed <- jmvcore::OptionNumber$new(
                "rngSeed",
                rngSeed,
                default=8675309)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..compare)
            self$.addOption(private$..obs)
            self$.addOption(private$..exp)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcTot)
            self$.addOption(private$..reps)
            self$.addOption(private$..dotHist)
            self$.addOption(private$..showCounts)
            self$.addOption(private$..seedBool)
            self$.addOption(private$..rngSeed)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        compare = function() private$..compare$value,
        obs = function() private$..obs$value,
        exp = function() private$..exp$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcTot = function() private$..pcTot$value,
        reps = function() private$..reps$value,
        dotHist = function() private$..dotHist$value,
        showCounts = function() private$..showCounts$value,
        seedBool = function() private$..seedBool$value,
        rngSeed = function() private$..rngSeed$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..compare = NA,
        ..obs = NA,
        ..exp = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcTot = NA,
        ..reps = NA,
        ..dotHist = NA,
        ..showCounts = NA,
        ..seedBool = NA,
        ..rngSeed = NA)
)

ContTabHTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ContTabHTestResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        x2tab = function() private$.items[["x2tab"]],
        textSimulations = function() private$.items[["textSimulations"]],
        Plot = function() private$.items[["Plot"]],
        simtable = function() private$.items[["simtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Contingency Table - Hypothesis Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Tables",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="x2tab",
                title="Comparative Measures",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "compare"),
                columns=list(
                    list(
                        `name`="t[x2]", 
                        `title`="", 
                        `type`="text", 
                        `content`="X\u00B2"),
                    list(
                        `name`="v[x2]", 
                        `title`="Value"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textSimulations",
                title="Simulated samples"))
            self$add(jmvcore::Image$new(
                options=options,
                name="Plot",
                title="Randomized Chi-Squared Statistics",
                renderFun=".permPlot",
                width=400,
                height=350,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "compare",
                    "reps",
                    "rngSeed",
                    "seedBool",
                    "dotHist",
                    "showCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="simtable",
                title="Simulation Results",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "compare",
                    "reps",
                    "rngSeed",
                    "seedBool"),
                columns=list(
                    list(
                        `name`="x2", 
                        `title`="X\u00B2", 
                        `type`="number"),
                    list(
                        `name`="reps", 
                        `title`="Reps", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

ContTabHTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ContTabHTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "ContTabHTest",
                version = c(1,0,0),
                options = options,
                results = ContTabHTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Contingency Table - Hypothesis Test
#'
#' 
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table (not
#'   necessary when providing a formula, see the examples)
#' @param cols the variable to use as the columns in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param counts the variable to use as the counts in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param compare \code{columns} or \code{rows} (default), compare
#'   columns/rows in difference of proportions or relative risks (2x2 tables)
#' @param obs \code{TRUE} or \code{FALSE} (default), provide the observed
#'   counts
#' @param exp \code{TRUE} or \code{FALSE} (default), provide the expected
#'   counts
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcTot \code{TRUE} or \code{FALSE} (default), provide total
#'   percentages
#' @param reps a number (default: 100), the number of parametric bootstraps
#' @param dotHist .
#' @param showCounts \code{TRUE} or \code{FALSE} (default), whether to print
#'   the count above each bar or dot stack of the simulation plot
#' @param seedBool \code{TRUE} or \code{FALSE} (default), whether to seed the
#'   random number generator
#' @param rngSeed a number (default: 8675309), for seeding the random number
#'   generator
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$x2tab} \tab \tab \tab \tab \tab a table of comparative measures \cr
#'   \code{results$textSimulations} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$Plot} \tab \tab \tab \tab \tab a plot showing the distribution of the differences in proportions \cr
#'   \code{results$simtable} \tab \tab \tab \tab \tab a table of the simulation results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
ContTabHTest <- function(
    data,
    rows,
    cols,
    counts = NULL,
    compare = "rows",
    obs = TRUE,
    exp = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    pcTot = FALSE,
    reps = 100,
    dotHist = "dotplot",
    showCounts = FALSE,
    seedBool = FALSE,
    rngSeed = 8675309) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ContTabHTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ContTabHTestOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        compare = compare,
        obs = obs,
        exp = exp,
        pcRow = pcRow,
        pcCol = pcCol,
        pcTot = pcTot,
        reps = reps,
        dotHist = dotHist,
        showCounts = showCounts,
        seedBool = seedBool,
        rngSeed = rngSeed)

    analysis <- ContTabHTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

