
# This file is automatically generated, you probably don't want to edit this

modelBasedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "modelBasedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            distro = "ndistro",
            dF = 30,
            areaBool = FALSE,
            obsStat = 0,
            tail = "right",
            CIBool = FALSE,
            confLevel = 95, ...) {

            super$initialize(
                package="Randomize",
                name="modelBased",
                requiresData=FALSE,
                ...)

            private$..distro <- jmvcore::OptionList$new(
                "distro",
                distro,
                options=list(
                    "ndistro",
                    "tdistro"),
                default="ndistro")
            private$..dF <- jmvcore::OptionInteger$new(
                "dF",
                dF,
                min=1,
                default=30)
            private$..areaBool <- jmvcore::OptionBool$new(
                "areaBool",
                areaBool,
                default=FALSE)
            private$..obsStat <- jmvcore::OptionNumber$new(
                "obsStat",
                obsStat,
                default=0)
            private$..tail <- jmvcore::OptionList$new(
                "tail",
                tail,
                options=list(
                    "right",
                    "left",
                    "both"),
                default="right")
            private$..CIBool <- jmvcore::OptionBool$new(
                "CIBool",
                CIBool,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=95,
                min=0)

            self$.addOption(private$..distro)
            self$.addOption(private$..dF)
            self$.addOption(private$..areaBool)
            self$.addOption(private$..obsStat)
            self$.addOption(private$..tail)
            self$.addOption(private$..CIBool)
            self$.addOption(private$..confLevel)
        }),
    active = list(
        distro = function() private$..distro$value,
        dF = function() private$..dF$value,
        areaBool = function() private$..areaBool$value,
        obsStat = function() private$..obsStat$value,
        tail = function() private$..tail$value,
        CIBool = function() private$..CIBool$value,
        confLevel = function() private$..confLevel$value),
    private = list(
        ..distro = NA,
        ..dF = NA,
        ..areaBool = NA,
        ..obsStat = NA,
        ..tail = NA,
        ..CIBool = NA,
        ..confLevel = NA)
)

modelBasedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "modelBasedResults",
    inherit = jmvcore::Group,
    active = list(
        textArea = function() private$.items[["textArea"]],
        Plot = function() private$.items[["Plot"]],
        areaTable = function() private$.items[["areaTable"]],
        textMultiplier = function() private$.items[["textMultiplier"]],
        multTable = function() private$.items[["multTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Model-Based Inference")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textArea",
                title="Calculate Probability"))
            self$add(jmvcore::Image$new(
                options=options,
                name="Plot",
                title="Probability density function",
                renderFun=".areaPlot",
                width=400,
                height=200,
                clearWith=list(
                    "distro",
                    "dF",
                    "hypTestBool",
                    "obsStat",
                    "tail")))
            self$add(jmvcore::Table$new(
                options=options,
                name="areaTable",
                title="Shaded area (p-value)",
                clearWith=list(
                    "distro",
                    "dF",
                    "hypTestBool",
                    "obsStat",
                    "tail"),
                columns=list(
                    list(
                        `name`="obsStat", 
                        `title`="Obs. Val", 
                        `type`="number"),
                    list(
                        `name`="area", 
                        `title`="Area (p-value)", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textMultiplier",
                title="CI multiplier"))
            self$add(jmvcore::Table$new(
                options=options,
                name="multTable",
                title="Critical value",
                clearWith=list(
                    "distro",
                    "dF",
                    "CIBool",
                    "confLevel"),
                columns=list(
                    list(
                        `name`="confLev", 
                        `title`="Confidence level (%)", 
                        `type`="number"),
                    list(
                        `name`="critVal", 
                        `title`="Multiplier", 
                        `type`="number", 
                        `format`="zto"))))}))

modelBasedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "modelBasedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "modelBased",
                version = c(1,0,0),
                options = options,
                results = modelBasedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Model-Based Inference
#'
#' 
#' @param distro .
#' @param dF a number (default: 30), degrees of freedom for T distro
#' @param areaBool \code{TRUE} or \code{FALSE} (default), whether to calculate
#'   area
#' @param obsStat a number (default: 0.0), the observed value of Z or T
#' @param tail .
#' @param CIBool \code{TRUE} or \code{FALSE} (default), whether to calculate
#'   p-value
#' @param confLevel a number (default: 95), the confidence level
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textArea} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$Plot} \tab \tab \tab \tab \tab a plot showing the area under probability density curve \cr
#'   \code{results$areaTable} \tab \tab \tab \tab \tab table with area under probability density curve \cr
#'   \code{results$textMultiplier} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$multTable} \tab \tab \tab \tab \tab a table with CI multiplier \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$areaTable$asDF}
#'
#' \code{as.data.frame(results$areaTable)}
#'
#' @export
modelBased <- function(
    distro = "ndistro",
    dF = 30,
    areaBool = FALSE,
    obsStat = 0,
    tail = "right",
    CIBool = FALSE,
    confLevel = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("modelBased requires jmvcore to be installed (restart may be required)")


    options <- modelBasedOptions$new(
        distro = distro,
        dF = dF,
        areaBool = areaBool,
        obsStat = obsStat,
        tail = tail,
        CIBool = CIBool,
        confLevel = confLevel)

    analysis <- modelBasedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

