
# This file is automatically generated, you probably don't want to edit this

pairedmeanCIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pairedmeanCIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            confLevel = 95,
            ciType = "bootperc",
            desc = FALSE,
            plots = FALSE,
            reps = 100,
            dotHist = "dotplot",
            showCounts = FALSE,
            seedBool = FALSE,
            rngSeed = 8675309, ...) {

            super$initialize(
                package="Randomize",
                name="pairedmeanCI",
                requiresData=TRUE,
                ...)

            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=95)
            private$..ciType <- jmvcore::OptionList$new(
                "ciType",
                ciType,
                options=list(
                    "bootperc",
                    "bootse"),
                default="bootperc")
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..reps <- jmvcore::OptionNumber$new(
                "reps",
                reps,
                default=100)
            private$..dotHist <- jmvcore::OptionList$new(
                "dotHist",
                dotHist,
                options=list(
                    "dotplot",
                    "histogram"),
                default="dotplot")
            private$..showCounts <- jmvcore::OptionBool$new(
                "showCounts",
                showCounts,
                default=FALSE)
            private$..seedBool <- jmvcore::OptionBool$new(
                "seedBool",
                seedBool,
                default=FALSE)
            private$..rngSeed <- jmvcore::OptionNumber$new(
                "rngSeed",
                rngSeed,
                default=8675309)

            self$.addOption(private$..pairs)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..ciType)
            self$.addOption(private$..desc)
            self$.addOption(private$..plots)
            self$.addOption(private$..reps)
            self$.addOption(private$..dotHist)
            self$.addOption(private$..showCounts)
            self$.addOption(private$..seedBool)
            self$.addOption(private$..rngSeed)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        confLevel = function() private$..confLevel$value,
        ciType = function() private$..ciType$value,
        desc = function() private$..desc$value,
        plots = function() private$..plots$value,
        reps = function() private$..reps$value,
        dotHist = function() private$..dotHist$value,
        showCounts = function() private$..showCounts$value,
        seedBool = function() private$..seedBool$value,
        rngSeed = function() private$..rngSeed$value),
    private = list(
        ..pairs = NA,
        ..confLevel = NA,
        ..ciType = NA,
        ..desc = NA,
        ..plots = NA,
        ..reps = NA,
        ..dotHist = NA,
        ..showCounts = NA,
        ..seedBool = NA,
        ..rngSeed = NA)
)

pairedmeanCIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pairedmeanCIResults",
    inherit = jmvcore::Group,
    active = list(
        desc = function() private$.items[["desc"]],
        descplot = function() private$.items[["descplot"]],
        simplot = function() private$.items[["simplot"]],
        CITable = function() private$.items[["CITable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Paired Means - Confidence Interval")
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptives",
                visible="(desc)",
                clearWith=list(
                    "pairs"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `content`=".", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="m", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="descplot",
                title="Descriptive Plots",
                items="(pairs)",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        desc = function() private$.items[["desc"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="no title")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="desc",
                                visible="(plots)",
                                renderFun=".descplot",
                                clearWith=list()))}))$new(options=options)))
            self$add(jmvcore::Image$new(
                options=options,
                name="simplot",
                title="Bootstrap mean differences",
                renderFun=".bootPlot",
                width=400,
                height=350,
                clearWith=list(
                    "pairs",
                    "confLevel",
                    "ciType",
                    "reps",
                    "rngSeed",
                    "seedBool",
                    "dotHist",
                    "showCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="CITable",
                title="Paired Means - Confidence Interval",
                rows="(pairs)",
                clearWith=list(
                    "confLevel",
                    "ciType",
                    "rngSeed",
                    "seedBool",
                    "reps"),
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="var2", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="reps", 
                        `title`="Reps", 
                        `type`="integer"),
                    list(
                        `name`="obsDiff", 
                        `title`="Observed mean difference", 
                        `type`="number"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval", 
                        `type`="number", 
                        `format`="zto"))))}))

pairedmeanCIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pairedmeanCIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "pairedmeanCI",
                version = c(1,0,0),
                options = options,
                results = pairedmeanCIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Paired Means - Confidence Interval
#'
#' Bootstrap CI for difference in paired means.
#' 
#'
#' @examples
#' data('sleep')
#'
#' pairedmeanCI(pairs = list(list(i1 = 'extra', i2 = 'group')), data = sleep)
#'
#' @param data the data as a data frame
#' @param pairs a list sepcifying the pairs of measurements in the data
#' @param confLevel a number (default: 95), the confidence level
#' @param ciType .
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param plots \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   plots
#' @param reps a number (default: 100), the number of parametric bootstraps
#' @param dotHist .
#' @param showCounts \code{TRUE} or \code{FALSE} (default), whether to print
#'   the count above each bar or dot stack of the simulation plot
#' @param seedBool \code{TRUE} or \code{FALSE} (default), whether to seed the
#'   random number generator
#' @param rngSeed a number (default: 8675309), for seeding the random number
#'   generator
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$desc} \tab \tab \tab \tab \tab a table containing the descriptives \cr
#'   \code{results$descplot} \tab \tab \tab \tab \tab descriptives plot \cr
#'   \code{results$simplot} \tab \tab \tab \tab \tab a plot showing the distribution of mean differences \cr
#'   \code{results$CITable} \tab \tab \tab \tab \tab a table containing the bootstrap CI results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$desc$asDF}
#'
#' \code{as.data.frame(results$desc)}
#'
#' @export
pairedmeanCI <- function(
    data,
    pairs,
    confLevel = 95,
    ciType = "bootperc",
    desc = FALSE,
    plots = FALSE,
    reps = 100,
    dotHist = "dotplot",
    showCounts = FALSE,
    seedBool = FALSE,
    rngSeed = 8675309) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pairedmeanCI requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- pairedmeanCIOptions$new(
        pairs = pairs,
        confLevel = confLevel,
        ciType = ciType,
        desc = desc,
        plots = plots,
        reps = reps,
        dotHist = dotHist,
        showCounts = showCounts,
        seedBool = seedBool,
        rngSeed = rngSeed)

    analysis <- pairedmeanCIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

