
# This file is automatically generated, you probably don't want to edit this

SingleMeanCIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SingleMeanCIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            resp = NULL,
            confLevel = 95,
            ciType = "bootperc",
            reps = 100,
            dotHist = "dotplot",
            seedBool = FALSE,
            rngSeed = 8675309, ...) {

            super$initialize(
                package="Randomize",
                name="SingleMeanCI",
                requiresData=TRUE,
                ...)

            private$..resp <- jmvcore::OptionVariable$new(
                "resp",
                resp,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=95)
            private$..ciType <- jmvcore::OptionList$new(
                "ciType",
                ciType,
                options=list(
                    "bootperc",
                    "bootse"),
                default="bootperc")
            private$..reps <- jmvcore::OptionNumber$new(
                "reps",
                reps,
                default=100)
            private$..dotHist <- jmvcore::OptionList$new(
                "dotHist",
                dotHist,
                options=list(
                    "dotplot",
                    "histogram"),
                default="dotplot")
            private$..seedBool <- jmvcore::OptionBool$new(
                "seedBool",
                seedBool,
                default=FALSE)
            private$..rngSeed <- jmvcore::OptionNumber$new(
                "rngSeed",
                rngSeed,
                default=8675309)

            self$.addOption(private$..resp)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..ciType)
            self$.addOption(private$..reps)
            self$.addOption(private$..dotHist)
            self$.addOption(private$..seedBool)
            self$.addOption(private$..rngSeed)
        }),
    active = list(
        resp = function() private$..resp$value,
        confLevel = function() private$..confLevel$value,
        ciType = function() private$..ciType$value,
        reps = function() private$..reps$value,
        dotHist = function() private$..dotHist$value,
        seedBool = function() private$..seedBool$value,
        rngSeed = function() private$..rngSeed$value),
    private = list(
        ..resp = NA,
        ..confLevel = NA,
        ..ciType = NA,
        ..reps = NA,
        ..dotHist = NA,
        ..seedBool = NA,
        ..rngSeed = NA)
)

SingleMeanCIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SingleMeanCIResults",
    inherit = jmvcore::Group,
    active = list(
        textSample = function() private$.items[["textSample"]],
        summtable = function() private$.items[["summtable"]],
        textSimulations = function() private$.items[["textSimulations"]],
        Plot = function() private$.items[["Plot"]],
        simtable = function() private$.items[["simtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Single Mean - Confidence Interval")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textSample",
                title="Original sample"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summtable",
                title="Summary Statistics",
                clearWith=list(
                    "resp"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textSimulations",
                title="Simulated samples"))
            self$add(jmvcore::Image$new(
                options=options,
                name="Plot",
                title="Bootstrap Proportions",
                renderFun=".bootPlot",
                width=400,
                height=350,
                clearWith=list(
                    "resp",
                    "confLevel",
                    "ciType",
                    "reps",
                    "seedBool",
                    "rngSeed",
                    "dotHist")))
            self$add(jmvcore::Table$new(
                options=options,
                name="simtable",
                title="Simulation Results",
                clearWith=list(
                    "resp",
                    "confLevel",
                    "ciType",
                    "reps",
                    "seedBool",
                    "rngSeed"),
                columns=list(
                    list(
                        `name`="reps", 
                        `title`="Reps", 
                        `type`="integer"),
                    list(
                        `name`="obsMean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval", 
                        `type`="number"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval", 
                        `type`="number"))))}))

SingleMeanCIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SingleMeanCIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "SingleMeanCI",
                version = c(1,0,0),
                options = options,
                results = SingleMeanCIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Single Mean - Confidence Interval
#'
#' 
#' @param data .
#' @param resp .
#' @param confLevel a number (default: 95), the confidence level
#' @param ciType .
#' @param reps a number (default: 100), the number of bootstraps
#' @param dotHist .
#' @param seedBool \code{TRUE} or \code{FALSE} (default), whether to seed the
#'   random number generator
#' @param rngSeed a number (default: 8675309), for seeding the random number
#'   generator
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textSample} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summtable} \tab \tab \tab \tab \tab a table of descriptives \cr
#'   \code{results$textSimulations} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$Plot} \tab \tab \tab \tab \tab a plot showing the distribution of the means \cr
#'   \code{results$simtable} \tab \tab \tab \tab \tab a table of the simulation results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summtable$asDF}
#'
#' \code{as.data.frame(results$summtable)}
#'
#' @export
SingleMeanCI <- function(
    data,
    resp,
    confLevel = 95,
    ciType = "bootperc",
    reps = 100,
    dotHist = "dotplot",
    seedBool = FALSE,
    rngSeed = 8675309) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SingleMeanCI requires jmvcore to be installed (restart may be required)")

    if ( ! missing(resp)) resp <- jmvcore::resolveQuo(jmvcore::enquo(resp))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(resp), resp, NULL))


    options <- SingleMeanCIOptions$new(
        resp = resp,
        confLevel = confLevel,
        ciType = ciType,
        reps = reps,
        dotHist = dotHist,
        seedBool = seedBool,
        rngSeed = rngSeed)

    analysis <- SingleMeanCIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

