
# This file is automatically generated, you probably don't want to edit this

SinglePropHTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SinglePropHTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            resp = NULL,
            areCounts = FALSE,
            testValue = 0.5,
            alt = "notequal",
            reps = 100,
            dotHist = "dotplot",
            seedBool = FALSE,
            rngSeed = 8675309, ...) {

            super$initialize(
                package="Randomize",
                name="SinglePropHTest",
                requiresData=TRUE,
                ...)

            private$..resp <- jmvcore::OptionVariable$new(
                "resp",
                resp,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..areCounts <- jmvcore::OptionBool$new(
                "areCounts",
                areCounts,
                default=FALSE)
            private$..testValue <- jmvcore::OptionNumber$new(
                "testValue",
                testValue,
                default=0.5)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "notequal",
                    "greater",
                    "less"),
                default="notequal")
            private$..reps <- jmvcore::OptionNumber$new(
                "reps",
                reps,
                default=100)
            private$..dotHist <- jmvcore::OptionList$new(
                "dotHist",
                dotHist,
                options=list(
                    "dotplot",
                    "histogram"),
                default="dotplot")
            private$..seedBool <- jmvcore::OptionBool$new(
                "seedBool",
                seedBool,
                default=FALSE)
            private$..rngSeed <- jmvcore::OptionNumber$new(
                "rngSeed",
                rngSeed,
                default=8675309)

            self$.addOption(private$..resp)
            self$.addOption(private$..areCounts)
            self$.addOption(private$..testValue)
            self$.addOption(private$..alt)
            self$.addOption(private$..reps)
            self$.addOption(private$..dotHist)
            self$.addOption(private$..seedBool)
            self$.addOption(private$..rngSeed)
        }),
    active = list(
        resp = function() private$..resp$value,
        areCounts = function() private$..areCounts$value,
        testValue = function() private$..testValue$value,
        alt = function() private$..alt$value,
        reps = function() private$..reps$value,
        dotHist = function() private$..dotHist$value,
        seedBool = function() private$..seedBool$value,
        rngSeed = function() private$..rngSeed$value),
    private = list(
        ..resp = NA,
        ..areCounts = NA,
        ..testValue = NA,
        ..alt = NA,
        ..reps = NA,
        ..dotHist = NA,
        ..seedBool = NA,
        ..rngSeed = NA)
)

SinglePropHTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SinglePropHTestResults",
    inherit = jmvcore::Group,
    active = list(
        textSample = function() private$.items[["textSample"]],
        summtable = function() private$.items[["summtable"]],
        textSimulations = function() private$.items[["textSimulations"]],
        Plot = function() private$.items[["Plot"]],
        simtable = function() private$.items[["simtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Single Proportion - Hypothesis Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textSample",
                title="Original sample"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summtable",
                title="Summary Statistics",
                clearWith=list(
                    "resp",
                    "areCounts"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="total", 
                        `title`="Total", 
                        `type`="integer"),
                    list(
                        `name`="prop", 
                        `title`="Proportion", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="textSimulations",
                title="Simulated samples"))
            self$add(jmvcore::Image$new(
                options=options,
                name="Plot",
                title="Parametric Bootstrap Proportions",
                renderFun=".bootPlot",
                width=400,
                height=350,
                clearWith=list(
                    "resp",
                    "areCounts",
                    "testValue",
                    "alt",
                    "reps",
                    "rngSeed",
                    "seedBool",
                    "dotHist")))
            self$add(jmvcore::Table$new(
                options=options,
                name="simtable",
                title="Simulation Results",
                clearWith=list(
                    "resp",
                    "areCounts",
                    "testValue",
                    "alt",
                    "reps",
                    "rngSeed",
                    "seedBool"),
                columns=list(
                    list(
                        `name`="obsProp", 
                        `title`="Proportion", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="reps", 
                        `title`="Reps", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

SinglePropHTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SinglePropHTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "SinglePropHTest",
                version = c(1,0,0),
                options = options,
                results = SinglePropHTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Single Proportion - Hypothesis Test
#'
#' 
#' @param data .
#' @param resp .
#' @param areCounts \code{TRUE} or \code{FALSE} (default), the variables are
#'   counts
#' @param testValue a number (default: 0.5), the value for the null hypothesis
#' @param alt .
#' @param reps a number (default: 100), the number of parametric bootstraps
#' @param dotHist .
#' @param seedBool \code{TRUE} or \code{FALSE} (default), whether to seed the
#'   random number generator
#' @param rngSeed a number (default: 8675309), for seeding the random number
#'   generator
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textSample} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summtable} \tab \tab \tab \tab \tab a table of the proportions \cr
#'   \code{results$textSimulations} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$Plot} \tab \tab \tab \tab \tab a plot showing the distribution of the proportions \cr
#'   \code{results$simtable} \tab \tab \tab \tab \tab a table of the simulation results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summtable$asDF}
#'
#' \code{as.data.frame(results$summtable)}
#'
#' @export
SinglePropHTest <- function(
    data,
    resp,
    areCounts = FALSE,
    testValue = 0.5,
    alt = "notequal",
    reps = 100,
    dotHist = "dotplot",
    seedBool = FALSE,
    rngSeed = 8675309) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SinglePropHTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(resp)) resp <- jmvcore::resolveQuo(jmvcore::enquo(resp))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(resp), resp, NULL))

    for (v in resp) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- SinglePropHTestOptions$new(
        resp = resp,
        areCounts = areCounts,
        testValue = testValue,
        alt = alt,
        reps = reps,
        dotHist = dotHist,
        seedBool = seedBool,
        rngSeed = rngSeed)

    analysis <- SinglePropHTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

