
# This file is automatically generated, you probably don't want to edit this

slopehtestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "slopehtestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL,
            hypothesis = "notequal",
            coef = FALSE,
            modelfit = FALSE,
            plots = FALSE,
            reps = 100,
            dotHist = "dotplot",
            showCounts = FALSE,
            seedBool = FALSE,
            rngSeed = 8675309, ...) {

            super$initialize(
                package="Randomize",
                name="slopehtest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..indep <- jmvcore::OptionVariable$new(
                "indep",
                indep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "notequal",
                    "greater",
                    "less"),
                default="notequal")
            private$..coef <- jmvcore::OptionBool$new(
                "coef",
                coef,
                default=FALSE)
            private$..modelfit <- jmvcore::OptionBool$new(
                "modelfit",
                modelfit,
                default=FALSE)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..reps <- jmvcore::OptionNumber$new(
                "reps",
                reps,
                default=100)
            private$..dotHist <- jmvcore::OptionList$new(
                "dotHist",
                dotHist,
                options=list(
                    "dotplot",
                    "histogram"),
                default="dotplot")
            private$..showCounts <- jmvcore::OptionBool$new(
                "showCounts",
                showCounts,
                default=FALSE)
            private$..seedBool <- jmvcore::OptionBool$new(
                "seedBool",
                seedBool,
                default=FALSE)
            private$..rngSeed <- jmvcore::OptionNumber$new(
                "rngSeed",
                rngSeed,
                default=8675309)

            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..coef)
            self$.addOption(private$..modelfit)
            self$.addOption(private$..plots)
            self$.addOption(private$..reps)
            self$.addOption(private$..dotHist)
            self$.addOption(private$..showCounts)
            self$.addOption(private$..seedBool)
            self$.addOption(private$..rngSeed)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value,
        hypothesis = function() private$..hypothesis$value,
        coef = function() private$..coef$value,
        modelfit = function() private$..modelfit$value,
        plots = function() private$..plots$value,
        reps = function() private$..reps$value,
        dotHist = function() private$..dotHist$value,
        showCounts = function() private$..showCounts$value,
        seedBool = function() private$..seedBool$value,
        rngSeed = function() private$..rngSeed$value),
    private = list(
        ..dep = NA,
        ..indep = NA,
        ..hypothesis = NA,
        ..coef = NA,
        ..modelfit = NA,
        ..plots = NA,
        ..reps = NA,
        ..dotHist = NA,
        ..showCounts = NA,
        ..seedBool = NA,
        ..rngSeed = NA)
)

slopehtestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "slopehtestResults",
    inherit = jmvcore::Group,
    active = list(
        coef = function() private$.items[["coef"]],
        modelfit = function() private$.items[["modelfit"]],
        linplot = function() private$.items[["linplot"]],
        simplot = function() private$.items[["simplot"]],
        htest = function() private$.items[["htest"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Slope (SLR) - Hypothesis Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="Model Coefficients",
                visible="(coef)",
                rows=2,
                clearWith=list(
                    "indep"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="est", 
                        `title`="Estimate", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelfit",
                title="Correlation, R\u00B2",
                visible="(modelfit)",
                rows="(dep)",
                clearWith=list(
                    "indep"),
                columns=list(
                    list(
                        `name`="r", 
                        `title`="r", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="linplot",
                title="Scatter plot with regression line",
                items="(dep)",
                clearWith=list(
                    "indep"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        lp = function() private$.items[["lp"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="lp",
                                visible="(plots)",
                                renderFun=".linplot",
                                clearWith=list()))}))$new(options=options)))
            self$add(jmvcore::Image$new(
                options=options,
                name="simplot",
                title="Randomized slopes",
                renderFun=".permPlot",
                width=400,
                height=350,
                clearWith=list(
                    "dep",
                    "indep",
                    "hypothesis",
                    "reps",
                    "rngSeed",
                    "seedBool",
                    "dotHist",
                    "showCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="htest",
                title="Slope - Hypothesis Test",
                rows="(dep)",
                clearWith=list(
                    "indep",
                    "hypothesis",
                    "rngSeed",
                    "seedBool",
                    "reps"),
                columns=list(
                    list(
                        `name`="b", 
                        `title`="Observed slope", 
                        `type`="number"),
                    list(
                        `name`="reps", 
                        `title`="Reps", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

slopehtestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "slopehtestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "slopehtest",
                version = c(1,0,0),
                options = options,
                results = slopehtestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Slope (SLR) - Hypothesis Test
#'
#' Permutation test for slope.
#' 
#'
#' @examples
#' data('faithful')
#'
#' slopehtest(dep = eruptions, indep = waiting, data = faithful)
#'
#' @param data the data as a data frame
#' @param dep the dependent variable (not necessary when using a formula, see
#'   the examples)
#' @param indep the independent variable (not necessary when using a formula,
#'   see the examples)
#' @param hypothesis \code{'notequal'} (default), \code{'greater'} or
#'   \code{'less'}, the alternative hypothesis; slope not equal to 0, slope
#'   greater than 0, or slope less than 0
#' @param coef \code{TRUE} or \code{FALSE} (default), provide model
#'   coefficients
#' @param modelfit \code{TRUE} or \code{FALSE} (default), provide correlation
#'   and R^2
#' @param plots \code{TRUE} or \code{FALSE} (default), provide scatter plot
#'   with regression line.
#' @param reps a number (default: 100), the number of parametric bootstraps
#' @param dotHist .
#' @param showCounts \code{TRUE} or \code{FALSE} (default), whether to print
#'   the count above each bar or dot stack of the simulation plot
#' @param seedBool \code{TRUE} or \code{FALSE} (default), whether to seed the
#'   random number generator
#' @param rngSeed a number (default: 8675309), for seeding the random number
#'   generator
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$coef} \tab \tab \tab \tab \tab a table containing the model coefficients \cr
#'   \code{results$modelfit} \tab \tab \tab \tab \tab a table containing the correlation and R^2 \cr
#'   \code{results$linplot} \tab \tab \tab \tab \tab an array of groups of plots \cr
#'   \code{results$simplot} \tab \tab \tab \tab \tab a plot showing the distribution of slopes \cr
#'   \code{results$htest} \tab \tab \tab \tab \tab a table containing the permutation test results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coef$asDF}
#'
#' \code{as.data.frame(results$coef)}
#'
#' @export
slopehtest <- function(
    data,
    dep,
    indep,
    hypothesis = "notequal",
    coef = FALSE,
    modelfit = FALSE,
    plots = FALSE,
    reps = 100,
    dotHist = "dotplot",
    showCounts = FALSE,
    seedBool = FALSE,
    rngSeed = 8675309,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("slopehtest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(dep))
            dep <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                required=TRUE)
        if (missing(indep))
            indep <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                subset="1")
    }

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indep), indep, NULL))


    options <- slopehtestOptions$new(
        dep = dep,
        indep = indep,
        hypothesis = hypothesis,
        coef = coef,
        modelfit = modelfit,
        plots = plots,
        reps = reps,
        dotHist = dotHist,
        showCounts = showCounts,
        seedBool = seedBool,
        rngSeed = rngSeed)

    analysis <- slopehtestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

