
# This file is automatically generated, you probably don't want to edit this

twomeanCIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "twomeanCIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            confLevel = 95,
            ciType = "bootperc",
            desc = FALSE,
            plots = FALSE,
            reps = 100,
            dotHist = "dotplot",
            seedBool = FALSE,
            rngSeed = 8675309, ...) {

            super$initialize(
                package="Randomize",
                name="twomeanCI",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariable$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=95)
            private$..ciType <- jmvcore::OptionList$new(
                "ciType",
                ciType,
                options=list(
                    "bootperc",
                    "bootse"),
                default="bootperc")
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..reps <- jmvcore::OptionNumber$new(
                "reps",
                reps,
                default=100)
            private$..dotHist <- jmvcore::OptionList$new(
                "dotHist",
                dotHist,
                options=list(
                    "dotplot",
                    "histogram"),
                default="dotplot")
            private$..seedBool <- jmvcore::OptionBool$new(
                "seedBool",
                seedBool,
                default=FALSE)
            private$..rngSeed <- jmvcore::OptionNumber$new(
                "rngSeed",
                rngSeed,
                default=8675309)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..ciType)
            self$.addOption(private$..desc)
            self$.addOption(private$..plots)
            self$.addOption(private$..reps)
            self$.addOption(private$..dotHist)
            self$.addOption(private$..seedBool)
            self$.addOption(private$..rngSeed)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        confLevel = function() private$..confLevel$value,
        ciType = function() private$..ciType$value,
        desc = function() private$..desc$value,
        plots = function() private$..plots$value,
        reps = function() private$..reps$value,
        dotHist = function() private$..dotHist$value,
        seedBool = function() private$..seedBool$value,
        rngSeed = function() private$..rngSeed$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..confLevel = NA,
        ..ciType = NA,
        ..desc = NA,
        ..plots = NA,
        ..reps = NA,
        ..dotHist = NA,
        ..seedBool = NA,
        ..rngSeed = NA)
)

twomeanCIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "twomeanCIResults",
    inherit = jmvcore::Group,
    active = list(
        desc = function() private$.items[["desc"]],
        descplot = function() private$.items[["descplot"]],
        simplot = function() private$.items[["simplot"]],
        CITable = function() private$.items[["CITable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two Means - Confidence Interval")
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Group Descriptives",
                visible="(desc)",
                rows="(vars)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="group[1]", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="num[1]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean[1]", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med[1]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd[1]", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="group[2]", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="num[2]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean[2]", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med[2]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd[2]", 
                        `title`="SD", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="descplot",
                title="Descriptive Plots",
                items="(vars)",
                clearWith=list(
                    "group"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        desc = function() private$.items[["desc"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="desc",
                                visible="(plots)",
                                renderFun=".descplot",
                                clearWith=list()))}))$new(options=options)))
            self$add(jmvcore::Image$new(
                options=options,
                name="simplot",
                title="Differences in bootstrap means",
                renderFun=".bootPlot",
                width=400,
                height=350,
                clearWith=list(
                    "group",
                    "vars",
                    "confLevel",
                    "ciType",
                    "reps",
                    "rngSeed",
                    "seedBool",
                    "dotHist")))
            self$add(jmvcore::Table$new(
                options=options,
                name="CITable",
                title="Simulation Results",
                rows="(vars)",
                clearWith=list(
                    "group",
                    "confLevel",
                    "ciType",
                    "rngSeed",
                    "seedBool",
                    "reps"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="reps", 
                        `title`="Reps", 
                        `type`="integer"),
                    list(
                        `name`="obsDiff", 
                        `title`="Observed Difference", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval", 
                        `type`="number", 
                        `format`="zto"))))}))

twomeanCIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "twomeanCIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Randomize",
                name = "twomeanCI",
                version = c(1,0,0),
                options = options,
                results = twomeanCIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Two Means - Confidence Interval
#'
#' Bootstrap CI for difference in means means-independent samples.
#' 
#'
#' @examples
#' data('ToothGrowth')
#'
#' ttestIS(formula = len ~ supp, data = ToothGrowth)
#'
#' #
#' #  INDEPENDENT SAMPLES T-TEST
#' #
#' #  Independent Samples T-Test
#' #  ----------------------------------------------------
#' #                          statistic    df      p
#' #  ----------------------------------------------------
#' #    len    Student's t         1.92    58.0    0.060
#' #  ----------------------------------------------------
#' #
#'
#' @param data the data as a data frame
#' @param vars the dependent variable (not necessary when using a formula, see
#'   the examples)
#' @param group the grouping variable with two levels (not necessary when
#'   using a formula, see the examples)
#' @param confLevel a number (default: 95), the confidence level
#' @param ciType .
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param plots \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   plots
#' @param reps a number (default: 100), the number of parametric bootstraps
#' @param dotHist .
#' @param seedBool \code{TRUE} or \code{FALSE} (default), whether to seed the
#'   random number generator
#' @param rngSeed a number (default: 8675309), for seeding the random number
#'   generator
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$desc} \tab \tab \tab \tab \tab a table containing the group descriptives \cr
#'   \code{results$descplot} \tab \tab \tab \tab \tab an array of groups of plots \cr
#'   \code{results$simplot} \tab \tab \tab \tab \tab a plot showing the distribution of the differences in proportions \cr
#'   \code{results$CITable} \tab \tab \tab \tab \tab a table containing the CI results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$desc$asDF}
#'
#' \code{as.data.frame(results$desc)}
#'
#' @export
twomeanCI <- function(
    data,
    vars,
    group,
    confLevel = 95,
    ciType = "bootperc",
    desc = FALSE,
    plots = FALSE,
    reps = 100,
    dotHist = "dotplot",
    seedBool = FALSE,
    rngSeed = 8675309,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("twomeanCI requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(vars))
            vars <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                required=TRUE)
        if (missing(group))
            group <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                subset="1")
    }

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- twomeanCIOptions$new(
        vars = vars,
        group = group,
        confLevel = confLevel,
        ciType = ciType,
        desc = desc,
        plots = plots,
        reps = reps,
        dotHist = dotHist,
        seedBool = seedBool,
        rngSeed = rngSeed)

    analysis <- twomeanCIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

