# grid dispatches makeContent by S3 class at draw time; register the
# method dynamically so it works regardless of how the NAMESPACE file is
# (re)generated by the jamovi compiler.
.onLoad <- function(libname, pkgname) {
    registerS3method("makeContent", "randomize_dotstack",
                     makeContent.randomize_dotstack,
                     envir = asNamespace("grid"))
}
